require('dotenv').config()


const VLC_PW = process.env.VLC_PW
const VLC_PORT = process.env.VLC_PORT || 8080

const DISCORD_CLIENTID = process.env.DISCORD_CLIENT || '853338108045426688'

const ANILIST_AUTH = process.env.ANILIST_AUTHTOKEN
const ANILIST_ID = process.env.ANILIST_CLIENT_ID
const ANILIST_SECRET = process.env.ANILIST_CLIENT_SECRET
const ANILIST_REDIRECT = process.env.ANILIST_REDIRECT
const ANILIST_USER = process.env.ANILIST_USERNAME
const ANILIST_TOKEN = process.env.ANILIST_JWT

module.exports = {
  VLC_PW,
  VLC_PORT,
  DISCORD_CLIENTID,
  ANILIST_AUTH,
  ANILIST_ID,
  ANILIST_REDIRECT,
  ANILIST_SECRET,
  ANILIST_USER,
  ANILIST_TOKEN
}